name: Builds documentation and checks coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build the app with MAVEN
        run: mvn package

      - name: Move documentation to projectreports
        run: |
          mkdir -p projectreports/apidocs
          mv target/apidocs/* projectreports/apidocs/

      - name: Upload documentation to FTP1
        run: |
          curl -T projectreports/apidocs/* ftp://ray-systems.pt --user documentationpa@docs-pa.ray-systems.pt:${{ secrets.FTP_DOC_USER_PASSWORD }}

      - name: Move coverage report to projectreports
        run: |
          mkdir -p projectreports/jacoco
          mv target/site/jacoco/* projectreports/jacoco/

      - name: Upload coverage report to FTP2
        run: |
          curl -T projectreports/jacoco/* ftp://ray-systems.pt --user coveragereports@coverage-pa.ray-systems.pt:${{ secrets.FTP_COV_USER_PASSWORD }}