name: Builds documentation and checks coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build the app with MAVEN
        run: mvn package

      - name: Commit and push documentation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f target/apidocs
          git commit -m 'ci: Update Documentation report [AUTOMATIC CI]'
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}

      - name: Commit and push coverage report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f target/site/jacoco
          git commit -m 'ci: Update coverage report [AUTOMATIC CI]'
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}