name: Builds documentation and checks coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build the app with MAVEN
        run: mvn package

      - name: Move documentation to projectreports
        run: |
          mkdir -p projectreports/apidocs
          mv target/apidocs/* projectreports/apidocs/

      - name: Upload documentation to documentation subdomain
        uses: GenieTim/ftp-action@v4.0.1
        with:
          host: ray-systems.pt
          user: ${{ secrets.FTP_DOC_USER }}
          password: ${{ secrets.FTP_DOC_USER_PASSWORD }}
          localDir: projectreports/apidocs

      - name: Move coverage report to projectreports
        run: |
          mkdir -p projectreports/jacoco
          mv target/site/jacoco/* projectreports/jacoco/

      - name: Upload coverage report to coverage subdomain
        uses: GenieTim/ftp-action@v4.0.1
        with:
          host: ray-systems.pt
          user: ${{ secrets.FTP_COV_USER }}
          password: ${{ secrets.FTP_COV_USER_PASSWORD }}
          localDir: projectreports/jacoco