name: Builds documentation and checks coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
      - name: Build the app with MAVEN
        run: mvn package
      - name: Upload a Documentation Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: documentation-artifact
          path: target/apidocs
      - name: Upload a coverage Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: coverage-artifact
          path: target/site/jacoco