name: Java CI with Maven (Run Unit Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name : Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run unit tests
        run: mvn test